# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_detail_search.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_detail_search_window(object):
    def setupUi(self, detail_search_window):
        detail_search_window.setObjectName("detail_search_window")
        detail_search_window.resize(220, 279)
        self.gridLayout = QtWidgets.QGridLayout(detail_search_window)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_ISBN = QtWidgets.QLabel(detail_search_window)
        self.label_ISBN.setObjectName("label_ISBN")
        self.horizontalLayout.addWidget(self.label_ISBN)
        self.lineEdit_ISBN = QtWidgets.QLineEdit(detail_search_window)
        self.lineEdit_ISBN.setObjectName("lineEdit_ISBN")
        self.horizontalLayout.addWidget(self.lineEdit_ISBN)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_book_name = QtWidgets.QLabel(detail_search_window)
        self.label_book_name.setObjectName("label_book_name")
        self.horizontalLayout_2.addWidget(self.label_book_name)
        self.lineEdit_book_name = QtWidgets.QLineEdit(detail_search_window)
        self.lineEdit_book_name.setObjectName("lineEdit_book_name")
        self.horizontalLayout_2.addWidget(self.lineEdit_book_name)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_author = QtWidgets.QLabel(detail_search_window)
        self.label_author.setObjectName("label_author")
        self.horizontalLayout_3.addWidget(self.label_author)
        self.lineEdit_author = QtWidgets.QLineEdit(detail_search_window)
        self.lineEdit_author.setObjectName("lineEdit_author")
        self.horizontalLayout_3.addWidget(self.lineEdit_author)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_translator = QtWidgets.QLabel(detail_search_window)
        self.label_translator.setObjectName("label_translator")
        self.horizontalLayout_4.addWidget(self.label_translator)
        self.lineEdit_translator = QtWidgets.QLineEdit(detail_search_window)
        self.lineEdit_translator.setObjectName("lineEdit_translator")
        self.horizontalLayout_4.addWidget(self.lineEdit_translator)
        self.gridLayout.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_class = QtWidgets.QLabel(detail_search_window)
        self.label_class.setObjectName("label_class")
        self.horizontalLayout_5.addWidget(self.label_class)
        self.comboBox_class1 = QtWidgets.QComboBox(detail_search_window)
        self.comboBox_class1.setObjectName("comboBox_class1")
        self.horizontalLayout_5.addWidget(self.comboBox_class1)
        self.label_2 = QtWidgets.QLabel(detail_search_window)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.comboBox_class2 = QtWidgets.QComboBox(detail_search_window)
        self.comboBox_class2.setObjectName("comboBox_class2")
        self.horizontalLayout_5.addWidget(self.comboBox_class2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_5, 4, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_price = QtWidgets.QLabel(detail_search_window)
        self.label_price.setObjectName("label_price")
        self.horizontalLayout_6.addWidget(self.label_price)
        self.spinBox_price1 = QtWidgets.QSpinBox(detail_search_window)
        self.spinBox_price1.setMaximum(9999)
        self.spinBox_price1.setObjectName("spinBox_price1")
        self.horizontalLayout_6.addWidget(self.spinBox_price1)
        self.label_9 = QtWidgets.QLabel(detail_search_window)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        self.spinBox_price2 = QtWidgets.QSpinBox(detail_search_window)
        self.spinBox_price2.setMaximum(9999)
        self.spinBox_price2.setObjectName("spinBox_price2")
        self.horizontalLayout_6.addWidget(self.spinBox_price2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_6, 5, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_stock = QtWidgets.QLabel(detail_search_window)
        self.label_stock.setObjectName("label_stock")
        self.horizontalLayout_7.addWidget(self.label_stock)
        self.comboBox_stock = QtWidgets.QComboBox(detail_search_window)
        self.comboBox_stock.setObjectName("comboBox_stock")
        self.horizontalLayout_7.addWidget(self.comboBox_stock)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_7, 6, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton_accept = QtWidgets.QPushButton(detail_search_window)
        self.pushButton_accept.setObjectName("pushButton_accept")
        self.horizontalLayout_8.addWidget(self.pushButton_accept)
        self.pushButton_cancel = QtWidgets.QPushButton(detail_search_window)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout_8.addWidget(self.pushButton_cancel)
        self.gridLayout.addLayout(self.horizontalLayout_8, 7, 0, 1, 1)

        self.retranslateUi(detail_search_window)
        QtCore.QMetaObject.connectSlotsByName(detail_search_window)

    def retranslateUi(self, detail_search_window):
        _translate = QtCore.QCoreApplication.translate
        detail_search_window.setWindowTitle(_translate("detail_search_window", "高级搜索"))
        self.label_ISBN.setText(_translate("detail_search_window", "ISBN"))
        self.label_book_name.setText(_translate("detail_search_window", "书名"))
        self.label_author.setText(_translate("detail_search_window", "作者"))
        self.label_translator.setText(_translate("detail_search_window", "译者"))
        self.label_class.setText(_translate("detail_search_window", "分类"))
        self.label_2.setText(_translate("detail_search_window", "-"))
        self.label_price.setText(_translate("detail_search_window", "价格"))
        self.label_9.setText(_translate("detail_search_window", "-"))
        self.label_stock.setText(_translate("detail_search_window", "库存"))
        self.pushButton_accept.setText(_translate("detail_search_window", "搜索"))
        self.pushButton_cancel.setText(_translate("detail_search_window", "取消"))
