# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_book_detail.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_book_detail(object):
    def setupUi(self, book_detail):
        book_detail.setObjectName("book_detail")
        book_detail.resize(487, 502)
        self.graphicsView = QtWidgets.QGraphicsView(book_detail)
        self.graphicsView.setGeometry(QtCore.QRect(10, 10, 194, 249))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setObjectName("graphicsView")
        self.label_intro = QtWidgets.QLabel(book_detail)
        self.label_intro.setGeometry(QtCore.QRect(10, 270, 36, 16))
        self.label_intro.setObjectName("label_intro")
        self.intro = QtWidgets.QTextBrowser(book_detail)
        self.intro.setGeometry(QtCore.QRect(10, 300, 461, 111))
        self.intro.setObjectName("intro")
        self.widget = QtWidgets.QWidget(book_detail)
        self.widget.setGeometry(QtCore.QRect(310, 460, 158, 25))
        self.widget.setObjectName("widget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_add2cart = QtWidgets.QPushButton(self.widget)
        self.pushButton_add2cart.setObjectName("pushButton_add2cart")
        self.horizontalLayout_6.addWidget(self.pushButton_add2cart)
        self.pushButton_cancel = QtWidgets.QPushButton(self.widget)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout_6.addWidget(self.pushButton_cancel)
        self.widget1 = QtWidgets.QWidget(book_detail)
        self.widget1.setGeometry(QtCore.QRect(256, 10, 211, 251))
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_book_name = QtWidgets.QLabel(self.widget1)
        self.label_book_name.setObjectName("label_book_name")
        self.horizontalLayout.addWidget(self.label_book_name)
        self.book_name = QtWidgets.QLabel(self.widget1)
        self.book_name.setObjectName("book_name")
        self.horizontalLayout.addWidget(self.book_name)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_author = QtWidgets.QLabel(self.widget1)
        self.label_author.setObjectName("label_author")
        self.horizontalLayout_2.addWidget(self.label_author)
        self.author = QtWidgets.QLabel(self.widget1)
        self.author.setObjectName("author")
        self.horizontalLayout_2.addWidget(self.author)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_press = QtWidgets.QLabel(self.widget1)
        self.label_press.setObjectName("label_press")
        self.horizontalLayout_3.addWidget(self.label_press)
        self.press = QtWidgets.QLabel(self.widget1)
        self.press.setObjectName("press")
        self.horizontalLayout_3.addWidget(self.press)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_pressdata = QtWidgets.QLabel(self.widget1)
        self.label_pressdata.setObjectName("label_pressdata")
        self.horizontalLayout_4.addWidget(self.label_pressdata)
        self.pressdate = QtWidgets.QLabel(self.widget1)
        self.pressdate.setObjectName("pressdate")
        self.horizontalLayout_4.addWidget(self.pressdate)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_ISBN = QtWidgets.QLabel(self.widget1)
        self.label_ISBN.setObjectName("label_ISBN")
        self.horizontalLayout_5.addWidget(self.label_ISBN)
        self.ISBN = QtWidgets.QLabel(self.widget1)
        self.ISBN.setObjectName("ISBN")
        self.horizontalLayout_5.addWidget(self.ISBN)
        self.verticalLayout.addLayout(self.horizontalLayout_5)

        self.retranslateUi(book_detail)
        QtCore.QMetaObject.connectSlotsByName(book_detail)

    def retranslateUi(self, book_detail):
        _translate = QtCore.QCoreApplication.translate
        book_detail.setWindowTitle(_translate("book_detail", "详细信息"))
        self.label_intro.setText(_translate("book_detail", "简介："))
        self.pushButton_add2cart.setText(_translate("book_detail", "加入购物车"))
        self.pushButton_cancel.setText(_translate("book_detail", "取消"))
        self.label_book_name.setText(_translate("book_detail", "书名："))
        self.book_name.setText(_translate("book_detail", "书名"))
        self.label_author.setText(_translate("book_detail", "作者/译者："))
        self.author.setText(_translate("book_detail", "作者/译者"))
        self.label_press.setText(_translate("book_detail", "出版社："))
        self.press.setText(_translate("book_detail", "出版社"))
        self.label_pressdata.setText(_translate("book_detail", "出版日期："))
        self.pressdate.setText(_translate("book_detail", "出版日期"))
        self.label_ISBN.setText(_translate("book_detail", "ISBN："))
        self.ISBN.setText(_translate("book_detail", "ISBN"))
