# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_confirm_order.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_confirm_order(object):
    def setupUi(self, confirm_order):
        confirm_order.setObjectName("confirm_order")
        confirm_order.resize(526, 372)
        self.gridLayout = QtWidgets.QGridLayout(confirm_order)
        self.gridLayout.setVerticalSpacing(25)
        self.gridLayout.setObjectName("gridLayout")
        self.label_u_account = QtWidgets.QLabel(confirm_order)
        self.label_u_account.setObjectName("label_u_account")
        self.gridLayout.addWidget(self.label_u_account, 0, 0, 1, 1)
        self.u_account = QtWidgets.QLabel(confirm_order)
        self.u_account.setObjectName("u_account")
        self.gridLayout.addWidget(self.u_account, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(210, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(155, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 3, 1, 2)
        self.label_u_nickname = QtWidgets.QLabel(confirm_order)
        self.label_u_nickname.setObjectName("label_u_nickname")
        self.gridLayout.addWidget(self.label_u_nickname, 1, 0, 1, 1)
        self.u_nickname = QtWidgets.QLabel(confirm_order)
        self.u_nickname.setObjectName("u_nickname")
        self.gridLayout.addWidget(self.u_nickname, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(210, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(155, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 3, 1, 2)
        self.label_u_telephone = QtWidgets.QLabel(confirm_order)
        self.label_u_telephone.setObjectName("label_u_telephone")
        self.gridLayout.addWidget(self.label_u_telephone, 2, 0, 1, 1)
        self.u_telephone = QtWidgets.QLabel(confirm_order)
        self.u_telephone.setObjectName("u_telephone")
        self.gridLayout.addWidget(self.u_telephone, 2, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(210, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 2, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(155, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 2, 3, 1, 2)
        self.comboBox_address = QtWidgets.QComboBox(confirm_order)
        self.comboBox_address.setObjectName("comboBox_address")
        self.comboBox_address.addItem("")
        self.comboBox_address.addItem("")
        self.comboBox_address.addItem("")
        self.gridLayout.addWidget(self.comboBox_address, 3, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(261, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 3, 1, 1, 2)
        spacerItem7 = QtWidgets.QSpacerItem(155, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 3, 3, 1, 2)
        self.textBrowser = QtWidgets.QTextBrowser(confirm_order)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 4, 0, 1, 5)
        spacerItem8 = QtWidgets.QSpacerItem(122, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem8, 5, 0, 1, 2)
        spacerItem9 = QtWidgets.QSpacerItem(275, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem9, 5, 2, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_price = QtWidgets.QLabel(confirm_order)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_price.setFont(font)
        self.label_price.setObjectName("label_price")
        self.horizontalLayout.addWidget(self.label_price)
        self.price = QtWidgets.QLabel(confirm_order)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.price.setFont(font)
        self.price.setObjectName("price")
        self.horizontalLayout.addWidget(self.price)
        self.gridLayout.addLayout(self.horizontalLayout, 5, 4, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(122, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem10, 6, 0, 1, 2)
        spacerItem11 = QtWidgets.QSpacerItem(210, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem11, 6, 2, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_accept = QtWidgets.QPushButton(confirm_order)
        self.pushButton_accept.setObjectName("pushButton_accept")
        self.horizontalLayout_2.addWidget(self.pushButton_accept)
        self.pushButton_cancel = QtWidgets.QPushButton(confirm_order)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout_2.addWidget(self.pushButton_cancel)
        self.gridLayout.addLayout(self.horizontalLayout_2, 6, 3, 1, 2)

        self.retranslateUi(confirm_order)
        QtCore.QMetaObject.connectSlotsByName(confirm_order)

    def retranslateUi(self, confirm_order):
        _translate = QtCore.QCoreApplication.translate
        confirm_order.setWindowTitle(_translate("confirm_order", "确认订单"))
        self.label_u_account.setText(_translate("confirm_order", "用户名："))
        self.u_account.setText(_translate("confirm_order", "用户名"))
        self.label_u_nickname.setText(_translate("confirm_order", "昵称："))
        self.u_nickname.setText(_translate("confirm_order", "昵称"))
        self.label_u_telephone.setText(_translate("confirm_order", "电话："))
        self.u_telephone.setText(_translate("confirm_order", "电话"))
        self.comboBox_address.setItemText(0, _translate("confirm_order", "地址1"))
        self.comboBox_address.setItemText(1, _translate("confirm_order", "地址2"))
        self.comboBox_address.setItemText(2, _translate("confirm_order", "其他地址"))
        self.label_price.setText(_translate("confirm_order", "总价："))
        self.price.setText(_translate("confirm_order", "价格"))
        self.pushButton_accept.setText(_translate("confirm_order", "确认支付"))
        self.pushButton_cancel.setText(_translate("confirm_order", "取消"))
