# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_edit_user_profile.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_edit_user_profile(object):
    def setupUi(self, edit_user_profile):
        edit_user_profile.setObjectName("edit_user_profile")
        edit_user_profile.resize(519, 429)
        self.gridLayout = QtWidgets.QGridLayout(edit_user_profile)
        self.gridLayout.setContentsMargins(20, 20, 6, -1)
        self.gridLayout.setVerticalSpacing(33)
        self.gridLayout.setObjectName("gridLayout")
        self.label_u_account = QtWidgets.QLabel(edit_user_profile)
        self.label_u_account.setObjectName("label_u_account")
        self.gridLayout.addWidget(self.label_u_account, 0, 0, 1, 1)
        self.u_account = QtWidgets.QLabel(edit_user_profile)
        self.u_account.setObjectName("u_account")
        self.gridLayout.addWidget(self.u_account, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(57, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.label_u_telephone = QtWidgets.QLabel(edit_user_profile)
        self.label_u_telephone.setObjectName("label_u_telephone")
        self.gridLayout.addWidget(self.label_u_telephone, 0, 3, 1, 1)
        self.u_telephone = QtWidgets.QLineEdit(edit_user_profile)
        self.u_telephone.setObjectName("u_telephone")
        self.gridLayout.addWidget(self.u_telephone, 0, 4, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(32, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 6, 1, 2)
        self.label_u_nickname = QtWidgets.QLabel(edit_user_profile)
        self.label_u_nickname.setObjectName("label_u_nickname")
        self.gridLayout.addWidget(self.label_u_nickname, 1, 0, 1, 1)
        self.u_nickname = QtWidgets.QLineEdit(edit_user_profile)
        self.u_nickname.setObjectName("u_nickname")
        self.gridLayout.addWidget(self.u_nickname, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(57, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 2, 1, 1)
        self.label_u_email = QtWidgets.QLabel(edit_user_profile)
        self.label_u_email.setObjectName("label_u_email")
        self.gridLayout.addWidget(self.label_u_email, 1, 3, 1, 1)
        self.u_email = QtWidgets.QLineEdit(edit_user_profile)
        self.u_email.setObjectName("u_email")
        self.gridLayout.addWidget(self.u_email, 1, 4, 1, 2)
        spacerItem3 = QtWidgets.QSpacerItem(32, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 6, 1, 2)
        self.label_u_name = QtWidgets.QLabel(edit_user_profile)
        self.label_u_name.setObjectName("label_u_name")
        self.gridLayout.addWidget(self.label_u_name, 2, 0, 1, 1)
        self.u_name = QtWidgets.QLabel(edit_user_profile)
        self.u_name.setObjectName("u_name")
        self.gridLayout.addWidget(self.u_name, 2, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(57, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 2, 2, 1, 1)
        self.label_u_address1 = QtWidgets.QLabel(edit_user_profile)
        self.label_u_address1.setObjectName("label_u_address1")
        self.gridLayout.addWidget(self.label_u_address1, 3, 0, 1, 1)
        self.u_address1 = QtWidgets.QPlainTextEdit(edit_user_profile)
        self.u_address1.setObjectName("u_address1")
        self.gridLayout.addWidget(self.u_address1, 3, 1, 1, 7)
        self.label_u_address2 = QtWidgets.QLabel(edit_user_profile)
        self.label_u_address2.setObjectName("label_u_address2")
        self.gridLayout.addWidget(self.label_u_address2, 4, 0, 1, 1)
        self.u_address2 = QtWidgets.QPlainTextEdit(edit_user_profile)
        self.u_address2.setObjectName("u_address2")
        self.gridLayout.addWidget(self.u_address2, 4, 1, 1, 7)
        spacerItem5 = QtWidgets.QSpacerItem(310, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 5, 0, 1, 4)
        self.pushButton_accept = QtWidgets.QPushButton(edit_user_profile)
        self.pushButton_accept.setObjectName("pushButton_accept")
        self.gridLayout.addWidget(self.pushButton_accept, 5, 4, 1, 1)
        self.pushButton_cancel = QtWidgets.QPushButton(edit_user_profile)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.gridLayout.addWidget(self.pushButton_cancel, 5, 5, 1, 2)
        spacerItem6 = QtWidgets.QSpacerItem(9, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 5, 7, 1, 1)
        self.gridLayout.setColumnStretch(7, 1)

        self.retranslateUi(edit_user_profile)
        QtCore.QMetaObject.connectSlotsByName(edit_user_profile)

    def retranslateUi(self, edit_user_profile):
        _translate = QtCore.QCoreApplication.translate
        edit_user_profile.setWindowTitle(_translate("edit_user_profile", "编辑个人信息"))
        self.label_u_account.setText(_translate("edit_user_profile", "用户名："))
        self.u_account.setText(_translate("edit_user_profile", "用户名"))
        self.label_u_telephone.setText(_translate("edit_user_profile", "电话："))
        self.label_u_nickname.setText(_translate("edit_user_profile", "昵称："))
        self.label_u_email.setText(_translate("edit_user_profile", "邮箱："))
        self.label_u_name.setText(_translate("edit_user_profile", "真实姓名："))
        self.u_name.setText(_translate("edit_user_profile", "真实姓名"))
        self.label_u_address1.setText(_translate("edit_user_profile", "收获地址1："))
        self.label_u_address2.setText(_translate("edit_user_profile", "收获地址2："))
        self.pushButton_accept.setText(_translate("edit_user_profile", "保存"))
        self.pushButton_cancel.setText(_translate("edit_user_profile", "取消"))
