# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_edit_book_detail.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_edit_book_detail(object):
    def setupUi(self, edit_book_detail):
        edit_book_detail.setObjectName("edit_book_detail")
        edit_book_detail.resize(538, 603)
        self.label_intro = QtWidgets.QLabel(edit_book_detail)
        self.label_intro.setGeometry(QtCore.QRect(40, 380, 36, 16))
        self.label_intro.setObjectName("label_intro")
        self.intro = QtWidgets.QPlainTextEdit(edit_book_detail)
        self.intro.setGeometry(QtCore.QRect(30, 410, 481, 121))
        self.intro.setObjectName("intro")
        self.layoutWidget = QtWidgets.QWidget(edit_book_detail)
        self.layoutWidget.setGeometry(QtCore.QRect(290, 560, 239, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_upload = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_upload.setObjectName("pushButton_upload")
        self.horizontalLayout.addWidget(self.pushButton_upload)
        self.pushButton_save = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_save.setObjectName("pushButton_save")
        self.horizontalLayout.addWidget(self.pushButton_save)
        self.pushButton_cancel = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout.addWidget(self.pushButton_cancel)
        self.picture = QtWidgets.QLabel(edit_book_detail)
        self.picture.setGeometry(QtCore.QRect(20, 50, 191, 271))
        self.picture.setText("")
        self.picture.setPixmap(QtGui.QPixmap("../icon/background.jpg"))
        self.picture.setScaledContents(True)
        self.picture.setObjectName("picture")
        self.layoutWidget1 = QtWidgets.QWidget(edit_book_detail)
        self.layoutWidget1.setGeometry(QtCore.QRect(237, 26, 271, 371))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_book_name = QtWidgets.QLabel(self.layoutWidget1)
        self.label_book_name.setObjectName("label_book_name")
        self.gridLayout.addWidget(self.label_book_name, 0, 0, 1, 1)
        self.lineEdit_book_name = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_book_name.setObjectName("lineEdit_book_name")
        self.gridLayout.addWidget(self.lineEdit_book_name, 0, 1, 1, 2)
        self.label_author = QtWidgets.QLabel(self.layoutWidget1)
        self.label_author.setObjectName("label_author")
        self.gridLayout.addWidget(self.label_author, 1, 0, 1, 1)
        self.lineEdit_author = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_author.setObjectName("lineEdit_author")
        self.gridLayout.addWidget(self.lineEdit_author, 1, 1, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.lineEdit_translator = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_translator.setObjectName("lineEdit_translator")
        self.gridLayout.addWidget(self.lineEdit_translator, 2, 1, 1, 2)
        self.label_press = QtWidgets.QLabel(self.layoutWidget1)
        self.label_press.setObjectName("label_press")
        self.gridLayout.addWidget(self.label_press, 3, 0, 1, 1)
        self.lineEdit_press = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_press.setObjectName("lineEdit_press")
        self.gridLayout.addWidget(self.lineEdit_press, 3, 1, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.comboBox_class1 = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_class1.setObjectName("comboBox_class1")
        self.gridLayout.addWidget(self.comboBox_class1, 4, 1, 1, 1)
        self.comboBox_class2 = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_class2.setObjectName("comboBox_class2")
        self.gridLayout.addWidget(self.comboBox_class2, 4, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.lineEdit_class1 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_class1.setObjectName("lineEdit_class1")
        self.gridLayout.addWidget(self.lineEdit_class1, 5, 1, 1, 1)
        self.lineEdit_class2 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_class2.setObjectName("lineEdit_class2")
        self.gridLayout.addWidget(self.lineEdit_class2, 5, 2, 1, 1)
        self.label_ISBN = QtWidgets.QLabel(self.layoutWidget1)
        self.label_ISBN.setObjectName("label_ISBN")
        self.gridLayout.addWidget(self.label_ISBN, 6, 0, 1, 1)
        self.lineEdit_ISBN = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_ISBN.setObjectName("lineEdit_ISBN")
        self.gridLayout.addWidget(self.lineEdit_ISBN, 6, 1, 1, 2)
        self.label_pressdata = QtWidgets.QLabel(self.layoutWidget1)
        self.label_pressdata.setObjectName("label_pressdata")
        self.gridLayout.addWidget(self.label_pressdata, 7, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 8, 0, 1, 1)
        self.lineEdit_version = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_version.setObjectName("lineEdit_version")
        self.gridLayout.addWidget(self.lineEdit_version, 8, 1, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 9, 0, 1, 1)
        self.lineEdit_stock = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_stock.setObjectName("lineEdit_stock")
        self.gridLayout.addWidget(self.lineEdit_stock, 9, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 10, 0, 1, 1)
        self.lineEdit_price = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_price.setObjectName("lineEdit_price")
        self.gridLayout.addWidget(self.lineEdit_price, 10, 1, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 11, 0, 1, 1)
        self.lineEdit_vip_price = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_vip_price.setObjectName("lineEdit_vip_price")
        self.gridLayout.addWidget(self.lineEdit_vip_price, 11, 1, 1, 2)
        self.dateEdit_pressdate = QtWidgets.QDateEdit(self.layoutWidget1)
        self.dateEdit_pressdate.setObjectName("dateEdit_pressdate")
        self.gridLayout.addWidget(self.dateEdit_pressdate, 7, 1, 1, 1)

        self.retranslateUi(edit_book_detail)
        QtCore.QMetaObject.connectSlotsByName(edit_book_detail)

    def retranslateUi(self, edit_book_detail):
        _translate = QtCore.QCoreApplication.translate
        edit_book_detail.setWindowTitle(_translate("edit_book_detail", "编辑图书"))
        self.label_intro.setText(_translate("edit_book_detail", "简介："))
        self.pushButton_upload.setText(_translate("edit_book_detail", "上传封面"))
        self.pushButton_save.setText(_translate("edit_book_detail", "保存"))
        self.pushButton_cancel.setText(_translate("edit_book_detail", "取消"))
        self.label_book_name.setText(_translate("edit_book_detail", "书名："))
        self.label_author.setText(_translate("edit_book_detail", "作者："))
        self.label_5.setText(_translate("edit_book_detail", "译者(可选)："))
        self.label_press.setText(_translate("edit_book_detail", "出版社："))
        self.label_4.setText(_translate("edit_book_detail", "类别："))
        self.label_6.setText(_translate("edit_book_detail", "新建类别(可选)："))
        self.label_ISBN.setText(_translate("edit_book_detail", "ISBN："))
        self.label_pressdata.setText(_translate("edit_book_detail", "出版日期："))
        self.label.setText(_translate("edit_book_detail", "版本号："))
        self.label_7.setText(_translate("edit_book_detail", "库存："))
        self.label_2.setText(_translate("edit_book_detail", "单价："))
        self.label_3.setText(_translate("edit_book_detail", "会员价："))
