# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_m_user_profile.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_m_user_profile(object):
    def setupUi(self, m_user_profile):
        m_user_profile.setObjectName("m_user_profile")
        m_user_profile.resize(560, 429)
        self.gridLayout = QtWidgets.QGridLayout(m_user_profile)
        self.gridLayout.setContentsMargins(20, 20, -1, -1)
        self.gridLayout.setVerticalSpacing(30)
        self.gridLayout.setObjectName("gridLayout")
        self.label_u_account = QtWidgets.QLabel(m_user_profile)
        self.label_u_account.setObjectName("label_u_account")
        self.gridLayout.addWidget(self.label_u_account, 0, 0, 1, 1)
        self.u_account = QtWidgets.QLabel(m_user_profile)
        self.u_account.setObjectName("u_account")
        self.gridLayout.addWidget(self.u_account, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(113, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.label_u_telephone = QtWidgets.QLabel(m_user_profile)
        self.label_u_telephone.setObjectName("label_u_telephone")
        self.gridLayout.addWidget(self.label_u_telephone, 0, 3, 1, 1)
        self.u_telephone = QtWidgets.QLabel(m_user_profile)
        self.u_telephone.setObjectName("u_telephone")
        self.gridLayout.addWidget(self.u_telephone, 0, 4, 1, 1)
        self.label_u_nickname = QtWidgets.QLabel(m_user_profile)
        self.label_u_nickname.setObjectName("label_u_nickname")
        self.gridLayout.addWidget(self.label_u_nickname, 1, 0, 1, 1)
        self.u_nickname = QtWidgets.QLabel(m_user_profile)
        self.u_nickname.setObjectName("u_nickname")
        self.gridLayout.addWidget(self.u_nickname, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(113, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)
        self.label_u_email = QtWidgets.QLabel(m_user_profile)
        self.label_u_email.setObjectName("label_u_email")
        self.gridLayout.addWidget(self.label_u_email, 1, 3, 1, 1)
        self.u_email = QtWidgets.QLabel(m_user_profile)
        self.u_email.setObjectName("u_email")
        self.gridLayout.addWidget(self.u_email, 1, 4, 1, 1)
        self.label_u_name = QtWidgets.QLabel(m_user_profile)
        self.label_u_name.setObjectName("label_u_name")
        self.gridLayout.addWidget(self.label_u_name, 2, 0, 1, 1)
        self.u_name = QtWidgets.QLabel(m_user_profile)
        self.u_name.setObjectName("u_name")
        self.gridLayout.addWidget(self.u_name, 2, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(113, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 2, 1, 1)
        self.label_vip_status = QtWidgets.QLabel(m_user_profile)
        self.label_vip_status.setObjectName("label_vip_status")
        self.gridLayout.addWidget(self.label_vip_status, 2, 3, 1, 1)
        self.vip_status = QtWidgets.QLabel(m_user_profile)
        self.vip_status.setObjectName("vip_status")
        self.gridLayout.addWidget(self.vip_status, 2, 4, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_u_address2 = QtWidgets.QLabel(m_user_profile)
        self.label_u_address2.setObjectName("label_u_address2")
        self.horizontalLayout.addWidget(self.label_u_address2)
        self.u_address2 = QtWidgets.QTextBrowser(m_user_profile)
        self.u_address2.setObjectName("u_address2")
        self.horizontalLayout.addWidget(self.u_address2)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 0, 1, 6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_u_address1 = QtWidgets.QLabel(m_user_profile)
        self.label_u_address1.setObjectName("label_u_address1")
        self.horizontalLayout_2.addWidget(self.label_u_address1)
        self.u_address1 = QtWidgets.QTextBrowser(m_user_profile)
        self.u_address1.setObjectName("u_address1")
        self.horizontalLayout_2.addWidget(self.u_address1)
        self.gridLayout.addLayout(self.horizontalLayout_2, 4, 0, 1, 6)
        spacerItem3 = QtWidgets.QSpacerItem(218, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 5, 0, 1, 4)
        self.pushButton_cart = QtWidgets.QPushButton(m_user_profile)
        self.pushButton_cart.setObjectName("pushButton_cart")
        self.gridLayout.addWidget(self.pushButton_cart, 5, 4, 1, 1)
        self.pushButton_order = QtWidgets.QPushButton(m_user_profile)
        self.pushButton_order.setObjectName("pushButton_order")
        self.gridLayout.addWidget(self.pushButton_order, 5, 5, 1, 1)

        self.retranslateUi(m_user_profile)
        QtCore.QMetaObject.connectSlotsByName(m_user_profile)

    def retranslateUi(self, m_user_profile):
        _translate = QtCore.QCoreApplication.translate
        m_user_profile.setWindowTitle(_translate("m_user_profile", "用户信息"))
        self.label_u_account.setText(_translate("m_user_profile", "用户名："))
        self.u_account.setText(_translate("m_user_profile", "用户名"))
        self.label_u_telephone.setText(_translate("m_user_profile", "电话："))
        self.u_telephone.setText(_translate("m_user_profile", "电话"))
        self.label_u_nickname.setText(_translate("m_user_profile", "昵称："))
        self.u_nickname.setText(_translate("m_user_profile", "昵称"))
        self.label_u_email.setText(_translate("m_user_profile", "邮箱："))
        self.u_email.setText(_translate("m_user_profile", "邮箱"))
        self.label_u_name.setText(_translate("m_user_profile", "真实姓名："))
        self.u_name.setText(_translate("m_user_profile", "真实姓名"))
        self.label_vip_status.setText(_translate("m_user_profile", "会员状态："))
        self.vip_status.setText(_translate("m_user_profile", "会员状态"))
        self.label_u_address2.setText(_translate("m_user_profile", "收获地址2："))
        self.label_u_address1.setText(_translate("m_user_profile", "收货地址1："))
        self.pushButton_cart.setText(_translate("m_user_profile", "查看购物车"))
        self.pushButton_order.setText(_translate("m_user_profile", "查看订单"))
