# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_manage.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_manage(object):
    def setupUi(self, manage):
        manage.setObjectName("manage")
        manage.resize(1243, 736)
        self.centralwidget = QtWidgets.QWidget(manage)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.class_label = QtWidgets.QLabel(self.centralwidget)
        self.class_label.setObjectName("class_label")
        self.gridLayout.addWidget(self.class_label, 0, 0, 1, 1)
        self.comboBox_class1 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_class1.setObjectName("comboBox_class1")
        self.gridLayout.addWidget(self.comboBox_class1, 0, 1, 1, 3)
        self.hypho_label = QtWidgets.QLabel(self.centralwidget)
        self.hypho_label.setObjectName("hypho_label")
        self.gridLayout.addWidget(self.hypho_label, 0, 4, 1, 1)
        self.comboBox_class2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_class2.setObjectName("comboBox_class2")
        self.gridLayout.addWidget(self.comboBox_class2, 0, 5, 1, 2)
        self.lineEdit_search = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_search.setObjectName("lineEdit_search")
        self.gridLayout.addWidget(self.lineEdit_search, 1, 0, 1, 6)
        self.pushButton_search = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_search.setObjectName("pushButton_search")
        self.gridLayout.addWidget(self.pushButton_search, 1, 6, 1, 1)
        self.radioButton_name = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_name.setChecked(True)
        self.radioButton_name.setObjectName("radioButton_name")
        self.gridLayout.addWidget(self.radioButton_name, 2, 0, 1, 2)
        self.radioButton_author = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_author.setObjectName("radioButton_author")
        self.gridLayout.addWidget(self.radioButton_author, 2, 2, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(68, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 6, 1, 1)
        self.label_filter = QtWidgets.QLabel(self.centralwidget)
        self.label_filter.setObjectName("label_filter")
        self.gridLayout.addWidget(self.label_filter, 3, 0, 1, 1)
        self.comboBox_filter = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_filter.setObjectName("comboBox_filter")
        self.gridLayout.addWidget(self.comboBox_filter, 3, 1, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(88, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 3, 4, 1, 3)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 4, 0, 1, 1)
        self.comboBox_sort = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_sort.setObjectName("comboBox_sort")
        self.gridLayout.addWidget(self.comboBox_sort, 4, 1, 1, 3)
        spacerItem2 = QtWidgets.QSpacerItem(88, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 4, 4, 1, 3)
        self.pushButton_detail_search = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_detail_search.setObjectName("pushButton_detail_search")
        self.gridLayout.addWidget(self.pushButton_detail_search, 5, 0, 1, 3)
        spacerItem3 = QtWidgets.QSpacerItem(148, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 5, 3, 1, 4)
        self.pushButton_add_book = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_add_book.setObjectName("pushButton_add_book")
        self.gridLayout.addWidget(self.pushButton_add_book, 6, 0, 1, 3)
        spacerItem4 = QtWidgets.QSpacerItem(148, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 6, 3, 1, 4)
        self.pushButton_press_manage = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_press_manage.setObjectName("pushButton_press_manage")
        self.gridLayout.addWidget(self.pushButton_press_manage, 7, 0, 1, 3)
        spacerItem5 = QtWidgets.QSpacerItem(148, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 7, 3, 1, 4)
        self.pushButton_user_manage = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_user_manage.setObjectName("pushButton_user_manage")
        self.gridLayout.addWidget(self.pushButton_user_manage, 8, 0, 1, 3)
        spacerItem6 = QtWidgets.QSpacerItem(148, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 8, 3, 1, 4)
        self.pushButton_order_manage = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_order_manage.setObjectName("pushButton_order_manage")
        self.gridLayout.addWidget(self.pushButton_order_manage, 9, 0, 1, 3)
        spacerItem7 = QtWidgets.QSpacerItem(148, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 9, 3, 1, 4)
        spacerItem8 = QtWidgets.QSpacerItem(20, 368, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem8, 10, 3, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_all_page = QtWidgets.QLabel(self.centralwidget)
        self.label_all_page.setObjectName("label_all_page")
        self.gridLayout_2.addWidget(self.label_all_page, 1, 8, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(10)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(110)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(100)
        self.tableWidget.verticalHeader().setMinimumSectionSize(25)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.tableWidget, 0, 0, 1, 11)
        self.pushButton_delete = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.gridLayout_2.addWidget(self.pushButton_delete, 1, 3, 1, 1)
        self.pushButton_last_page = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_last_page.setObjectName("pushButton_last_page")
        self.gridLayout_2.addWidget(self.pushButton_last_page, 1, 9, 1, 1)
        self.pushButton_up = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_up.setObjectName("pushButton_up")
        self.gridLayout_2.addWidget(self.pushButton_up, 1, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(158, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem9, 1, 4, 1, 1)
        self.pushButton_next_page = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_next_page.setObjectName("pushButton_next_page")
        self.gridLayout_2.addWidget(self.pushButton_next_page, 1, 10, 1, 1)
        self.pushButton_selectall = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_selectall.setObjectName("pushButton_selectall")
        self.gridLayout_2.addWidget(self.pushButton_selectall, 1, 0, 1, 1)
        self.label_current_page = QtWidgets.QLabel(self.centralwidget)
        self.label_current_page.setObjectName("label_current_page")
        self.gridLayout_2.addWidget(self.label_current_page, 1, 7, 1, 1)
        self.pushButton_down = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_down.setObjectName("pushButton_down")
        self.gridLayout_2.addWidget(self.pushButton_down, 1, 2, 1, 1)
        self.lineEdit_pagejump = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_pagejump.setObjectName("lineEdit_pagejump")
        self.gridLayout_2.addWidget(self.lineEdit_pagejump, 1, 5, 1, 1)
        self.pushButton_page_jump = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_page_jump.setObjectName("pushButton_page_jump")
        self.gridLayout_2.addWidget(self.pushButton_page_jump, 1, 6, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout.setStretch(1, 1)
        manage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(manage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1243, 23))
        self.menubar.setObjectName("menubar")
        manage.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(manage)
        self.statusbar.setObjectName("statusbar")
        manage.setStatusBar(self.statusbar)

        self.retranslateUi(manage)
        QtCore.QMetaObject.connectSlotsByName(manage)

    def retranslateUi(self, manage):
        _translate = QtCore.QCoreApplication.translate
        manage.setWindowTitle(_translate("manage", "书店管理系统"))
        self.class_label.setText(_translate("manage", "类别："))
        self.hypho_label.setText(_translate("manage", "-"))
        self.pushButton_search.setText(_translate("manage", "搜索"))
        self.radioButton_name.setText(_translate("manage", "按书名"))
        self.radioButton_author.setText(_translate("manage", "按作者"))
        self.label_filter.setText(_translate("manage", "显示："))
        self.label.setText(_translate("manage", "排序："))
        self.pushButton_detail_search.setText(_translate("manage", "高级搜索"))
        self.pushButton_add_book.setText(_translate("manage", "新增图书"))
        self.pushButton_press_manage.setText(_translate("manage", "出版社管理"))
        self.pushButton_user_manage.setText(_translate("manage", "用户管理"))
        self.pushButton_order_manage.setText(_translate("manage", "订单管理"))
        self.label_all_page.setText(_translate("manage", "共 1 页"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("manage", "封面"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("manage", "书名"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("manage", "作者"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("manage", "分类"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("manage", "出版社"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("manage", "单价"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("manage", "月销量"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("manage", "库存"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("manage", "状态"))
        self.pushButton_delete.setText(_translate("manage", "删除"))
        self.pushButton_last_page.setText(_translate("manage", "上一页"))
        self.pushButton_up.setText(_translate("manage", "上架"))
        self.pushButton_next_page.setText(_translate("manage", "下一页"))
        self.pushButton_selectall.setText(_translate("manage", "全选"))
        self.label_current_page.setText(_translate("manage", "第 1 页"))
        self.pushButton_down.setText(_translate("manage", "下架"))
        self.pushButton_page_jump.setText(_translate("manage", "跳转"))
